### ISSUE TITLE
Consider publishing the localstack chart to kubernetes/charts ?

### ISSUE THREAD

**Issue by diclophis** [everpeace/helm-charts#3]
Hello,

I am interested in making use of your localstack chart... I would be grateful if it were published in the official kubernetes/charts repo.

Do you have any interest in publishing to that repo, and or, would you mind someone else publishing it on your behalf?

**Comment by StevenACoffman** [comment]
@diclophis This repository is licensed under the MIT license, and the kubernetes/charts is Apache license. I am not a lawyer, but my understanding is that is legitimate. To be polite, I think we should try once more to get explicit permission though.

@everpeace Would you mind if someone republished it in the kubernetes/charts repo under an Apache license?

**Comment by everpeace** [comment]
@StevenACoffman @diclophis sorry for my absent.....

> Would you mind if someone republished it in the kubernetes/charts repo under an Apache license?

no.  Please go ahead.  I would be appreciated if you would cite my name `Shingo Omura <everpeace@gmail.com>` as the original developer of the chart.

**Comment by sidhuko** [comment]
Hey all, I've started a discussion on localstack and will post a working copy of the chart later once I've finished making it fit helm contribution guidelines, with your terms respected @everpeace. After assessing the work involved, without the localstack support we might have to reinvent docker images for security checks, strict tagging and other [technical requirements](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#technical-requirements) to get the chart into stable. Hopefully we can contribute an incubator in the meantime - please show some support on the issue! 👍 

https://github.com/localstack/localstack/issues/882

**Comment by StevenACoffman** [comment]
Nice. Possibly relevant is that I made a local ec2metadata service installable into minikube over at [gimme-mini-aws](https://github.com/StevenACoffman/gimme-aws-mini)

**Comment by samrocketman** [comment]
MIT licensing dictates that it needs to be contributed with the license.

**Comment by sidhuko** [comment]
We could add a line to say the MIT license doesn't apply to localstack chart once we approach that problem. Same way you would approach the problem using a chart in helm/chart within a licensed project.

**Comment by benvandenberg** [comment]
@sidhuko were you able to get a localstack chart created, that fits with the Helm contribution guidelines?

**Comment by nukepuppy** [comment]
Any progress on moving this over to kubernetes/charts?    kind of an edge case and since it's fairly useful to all.. would be good.

Is there anything community can do to assist here?

**Comment by sidhuko** [comment]
I've a draft but needs testing in multiple scenarios: https://github.com/sidhuko/charts/pull/1/files. Some changes on another chart were taking a long time to be accepted so I didn't proceed until it was accepted. 

I'll see if I can get a pull request on helm in a few weeks once I've made fixes. Help always welcome.

**Comment by samrocketman** [comment]
To be more clear.  The MIT license and Apache License are not incompatible.  An MIT licensed project can be completely relicensed to Apache 2 as long as the original MIT license is mentioned.  MIT license basically maintains that you don’t sue the author.  Other than that, it is a very open license (even open to a project being relicensed so that additional code falls under a new license and not the original MIT).

That’s what I meant by you only need include the original MIT license of the original source.  That doesn’t mean it can’t follow the Apache license from that point forward.

i.e. you can contribute it and you don’t need permission from anybody.  Permission is granted via the original MIT license and so long as you include that license you’re within your granted rights.

**Comment by diclophis** [comment]
What is the latest on this issue? Are we able to find an resolution to the license problem?

**Comment by everpeace** [comment]
I'm not so familiar with oss licenses.  What kind of actions can I do to help to solve this issue?

**Comment by samrocketman** [comment]
I am not a lawyer but have experience interacting with lawyers on these matters.

There's no license problem.  Maybe my original comment wasn't clear.

* https://github.com/helm/charts i.e. the "kubernetes charts" repo is Apache 2 licensed.
* https://github.com/everpeace/helm-charts (this repository) is MIT licensed

There's two options to resolve this.

# Option 1

Random person copies this code to kubernetes charts repository... so what has to happen?

Both licenses are compatible with each other.  If somebody who isn't @everpeace wants to copy all of the code into the kubernetes charts repository, they can.  They just need to include the original MIT license published by @everpeace in this repository to be covered.

# Option 2

@everpeace copies this code to kubernetes charts repository... so what has to happen?

Not much, really.  Since you're the original author (assuming no contributors) you can simply copy your code in and re-license it under Apache 2.  You just need to open a pull request.

I do not know what hoops you have to jump through to get it merged since I haven't contributed to kubernetes before.

None of this blocks @everpeace from doing whatever they want with their code (copying to kubernetes charts repository or not).  Hopefully, that makes more sense.

**Comment by samrocketman** [comment]
I wouldn't worry about contributors... their contributions are small.

**Comment by diclophis** [comment]
Thank you for all the work on this issue.
